apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-server:7.5.0
    init: confluentinc/confluent-init-container:2.7.0
  dataVolumeCapacity: 10Gi
  configOverrides:
    server:
      - auto.create.topics.enable=true
      - offsets.topic.replication.factor=1
      - transaction.state.log.replication.factor=1
      - transaction.state.log.min.isr=1
      - default.replication.factor=1
      - min.insync.replicas=1
  metricReporter:
    enabled: false
  dependencies:
    zookeeper:
      endpoint: zookeeper.confluent.svc.cluster.local:2181
  podTemplate:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi
